//! Track A application iter 2: Manning calibration sobre evento
//! Aluvión Atacama 2017 con channel DEM-derived.
//!
//! # Diferencia vs `calibrate_manning_huasco_2017` (iter 1)
//!
//! Iter 1 usó un channel sintético uniforme (slope constante 0.005,
//! bed plano descendente linealmente). Iter 2 reemplaza ese bed por
//! un perfil longitudinal REAL extraído del DEM 30 m del Río Huasco
//! (`papers/paper1_susceptibilidad/factors/06_rio_huasco/hydrology/
//! filled.tif`), caminado downstream desde el snap al main stem
//! cerca de la estación Santa Juana (lat -28.6719, lon -70.6464).
//!
//! El perfil real exhibe la firma típica del *pit-filled* DEM en
//! cauces semiáridos: dos drops verticales (5.2 m y 4.1 m
//! aproximadamente) separados por reaches largas casi-planas
//! (slope local ~ 3e-6 — esencialmente el filling profundo del
//! algoritmo de pit-fill). El integrated slope sigue siendo
//! físicamente sensato: 12.17 m de drop sobre 1805 m → mean slope
//! 0.674 %.
//!
//! # Twin experiment
//!
//! Mismo workflow que iter 1: forcing REAL DGA (serie diaria Q en
//! Santa Juana ventana 21 días alrededor de 2017-03-02 peak
//! 38.9 m³/s), target sintético generado con `n_true = 0.04`,
//! calibración por gradient descent desde `n_guess = 0.06`.
//!
//! El bed no-uniforme y los step jumps cambian la dinámica del
//! solver vs el caso linear-slope: cada reach plana se llena hasta
//! desbordar al siguiente step, lo que produce un wave train
//! decaying en lugar del pure Manning-normal-depth uniform flow.
//! El target h(midpoint, day_end) refleja esa dinámica más rica;
//! la calibración aún recupera Manning correctamente porque la
//! observación contiene información suficiente sobre la fricción
//! total integrada sobre el reach.
//!
//! Reproducir:
//! ```text
//! cargo run --release -p hydroflux-autograd \
//!   --example calibrate_manning_huasco_2017_dem
//! ```

use hydroflux_autograd::{
    Dual, Real,
    swe1d::{self, LeftBc, RightBc},
};

// --- Channel geometry: DEM-derived longitudinal profile -----------
//
// 60 samples uniformly spaced over 1805.5 m (dx = 30.6019 m).
// Mean slope 0.006740, fitted linear 0.007443, drop 12.169 m.
// Generated by examples/huasco_channel/extract_longitudinal_profile.py.
const HUASCO_BED_M: [f64; 60] = [
    490.4969, 488.8318, 488.0484, 488.0483, 488.0483, 488.0482, 488.0481, 488.0480, 488.0480,
    488.0479, 488.0478, 488.0477, 488.0476, 488.0475, 488.0474, 488.0473, 488.0472, 488.0471,
    488.0471, 488.0469, 488.0469, 488.0468, 488.0467, 488.0467, 488.0466, 488.0465, 488.0464,
    488.0464, 488.0463, 488.0462, 488.0462, 488.0461, 488.0460, 488.0460, 488.0459, 488.0458,
    486.8172, 484.6574, 482.4074, 481.8460, 479.5109, 478.3294, 478.3293, 478.3293, 478.3292,
    478.3291, 478.3290, 478.3289, 478.3289, 478.3288, 478.3287, 478.3286, 478.3285, 478.3284,
    478.3283, 478.3282, 478.3281, 478.3280, 478.3279, 478.3279,
];
const N_CELLS: usize = HUASCO_BED_M.len();
const TOTAL_LENGTH: f64 = 1805.5;
const DX: f64 = TOTAL_LENGTH / (N_CELLS as f64 - 1.0); // ≈ 30.6 m
const WIDTH: f64 = 30.0; // synthetic; DEM-derived cross-section width pendiente.
const G: f64 = 9.81;
const CFL: f64 = 0.4;
const BLOCK_SECONDS: f64 = 600.0;
// Effective slope for inflow boundary Manning normal depth.
// Use the fitted linear slope rather than per-cell slope (which is
// dominated by the long flat reaches between the two real drops).
const SLOPE_EFFECTIVE: f64 = 0.007443;

// --- Atacama 2017 observed daily Q [m³/s] at Santa Juana, ---------
// 2017-02-20 → 2017-03-12. Source: DGA station 3820003 via
// examples/santa_juana_qflx/output/santa_juana_qflx.parquet.
const Q_DAILY_M3S: [f64; 21] = [
    17.5, 18.7, 18.4, 18.5, 20.5, 31.9, 34.8, 35.5, 37.8, 38.8, 38.9, 38.1, 37.5, 37.5, 36.0, 36.0,
    35.2, 34.8, 34.9, 33.9, 33.6,
];

/// Manning normal depth for a wide channel given q (per unit width), n, S₀.
fn manning_normal_depth_t<T: Real>(q: T, n: T, slope: f64) -> T {
    (n * q * T::from_f64(1.0 / slope.sqrt())).powf(3.0 / 5.0)
}

/// Run the full 21-day sequence under the given `n` and inflow
/// series. Returns `h(midpoint, end-of-each-day)` — a length-21 series.
fn simulate_event<T: Real>(n: T, q_daily_m2s: &[T]) -> Vec<T> {
    let bed: Vec<f64> = HUASCO_BED_M.to_vec();
    // Warm start the state at Manning normal depth above the bed.
    let q0_val = q_daily_m2s[0];
    let h_n0 = manning_normal_depth_t(q0_val, n, SLOPE_EFFECTIVE);
    let mut h: Vec<T> = vec![h_n0; N_CELLS];
    let mut q: Vec<T> = vec![q0_val; N_CELLS];

    let mid = N_CELLS / 2;
    let mut h_at_mid_per_day = Vec::with_capacity(q_daily_m2s.len());

    for q_block in q_daily_m2s {
        let h_bc = manning_normal_depth_t(*q_block, n, SLOPE_EFFECTIVE);
        let (h_new, q_new, _) = swe1d::run(
            h,
            q,
            &bed,
            DX,
            BLOCK_SECONDS,
            n,
            G,
            CFL,
            LeftBc::Dirichlet { h: h_bc, q: *q_block },
            RightBc::Transmissive,
        );
        h_at_mid_per_day.push(h_new[mid]);
        h = h_new;
        q = q_new;
    }
    h_at_mid_per_day
}

fn main() {
    let n_true = 0.04_f64;
    let n_guess_initial = 0.06_f64;

    let q_min = Q_DAILY_M3S.iter().copied().fold(f64::INFINITY, f64::min);
    let q_peak = Q_DAILY_M3S.iter().copied().fold(0.0_f64, f64::max);

    println!("Track A application iter 2 — DEM-derived channel");
    println!(
        "Channel: {:.1} m, {} cells × {:.2} m, width {} m (synthetic), \
         fitted slope {:.5}",
        TOTAL_LENGTH, N_CELLS, DX, WIDTH, SLOPE_EFFECTIVE
    );
    println!(
        "Bed source: DEM 30 m filled, walked downstream from Santa Juana \
         snap. Drop {:.2} m over {:.1} m.",
        HUASCO_BED_M[0] - HUASCO_BED_M[N_CELLS - 1],
        TOTAL_LENGTH
    );
    println!(
        "Forcing: Santa Juana DGA daily Q (Atacama 2017 event), \
         {} days, Q ∈ [{:.1}, {:.1}] m³/s",
        Q_DAILY_M3S.len(),
        q_min,
        q_peak
    );
    println!(
        "True Manning n = {:.4}, initial guess = {:.4}",
        n_true, n_guess_initial
    );

    let q_daily_m2s_f64: Vec<f64> = Q_DAILY_M3S.iter().map(|q| q / WIDTH).collect();

    // Twin observation.
    let h_observed: Vec<f64> = simulate_event(n_true, &q_daily_m2s_f64);
    println!(
        "\n  {:>3} {:>6} {:>8} {:>10}",
        "day", "Q_m3s", "q_m2s", "h_obs [m]"
    );
    for (i, h_o) in h_observed.iter().enumerate() {
        println!(
            "  {:>3} {:>6.1} {:>8.4} {:>10.5}",
            i + 1,
            Q_DAILY_M3S[i],
            q_daily_m2s_f64[i],
            h_o
        );
    }

    // Calibration.
    let q_obs_d: Vec<Dual> = q_daily_m2s_f64.iter().map(|&q| Dual::constant(q)).collect();
    let h_obs_d: Vec<Dual> = h_observed.iter().map(|&h| Dual::constant(h)).collect();

    let mut n_guess = n_guess_initial;
    let lr_base = 5.0e-5_f64;
    let max_step = 5.0e-3_f64;
    let max_iters = 40;
    let tol = 1.0e-10_f64;

    println!(
        "\n{:>4} {:>10} {:>14} {:>14} {:>10}",
        "iter", "n_guess", "cost", "dCost/dn", "|err|"
    );

    let mut prev_cost = f64::INFINITY;
    let mut lr = lr_base;
    let mut final_n = n_guess;
    for iter in 0..max_iters {
        let n_dual = Dual::variable(n_guess);
        let h_sim = simulate_event(n_dual, &q_obs_d);

        let mut cost = Dual::constant(0.0);
        for (h_s, h_o) in h_sim.iter().zip(h_obs_d.iter()) {
            let diff = *h_s - *h_o;
            cost = cost + diff * diff;
        }
        let cost_val = cost.val;
        let grad = cost.dval;
        let abs_err = (n_guess - n_true).abs();
        println!(
            "{iter:>4} {n_guess:>10.6} {cost_val:>14.6e} {grad:>14.6e} {abs_err:>10.5}"
        );

        if cost_val < tol {
            println!("\nConverged: cost = {cost_val:.3e} < tol {tol:.0e}");
            final_n = n_guess;
            break;
        }
        if cost_val > prev_cost {
            lr *= 0.5;
        }
        prev_cost = cost_val;
        let raw_step = lr * grad;
        let clamped = raw_step.signum() * raw_step.abs().min(max_step);
        n_guess -= clamped;
        n_guess = n_guess.max(1.0e-4);
        final_n = n_guess;
    }

    println!(
        "\nFinal: n_recovered = {:.6}, n_true = {:.4}, |err| = {:.3e}",
        final_n,
        n_true,
        (final_n - n_true).abs()
    );
    let lit_lo = 0.035_f64;
    let lit_hi = 0.050_f64;
    let in_range = final_n >= lit_lo && final_n <= lit_hi;
    println!(
        "Literature envelope Chow 1959 [gravel-bed Andean]: n ∈ [{lit_lo:.3}, {lit_hi:.3}]"
    );
    println!(
        "Recovered n {} the literature envelope.",
        if in_range { "✓ inside" } else { "✗ OUTSIDE" }
    );
}
