# fig02_verification.R — methods-paper Figure 2.
#
# Three-panel verification figure for the 2D solver (§3), each panel
# overlaying the simulated profile on the analytical reference:
#
#   (a) Stoker/Ritter dam-break on a dry bed (transient rarefaction +
#       dry front), t = 4 s.
#   (b) MacDonald uniform flow (well-balanced steady state on a sloped
#       bed with Manning friction).
#   (c) Thacker oscillating paraboloid (transient with a moving wet/dry
#       shoreline on a curved bed), centre-row slice at t = T/2.
#
# Inputs (generated by `gen_verification_data` example):
#   papers/01_review/figures/data/verif_{stoker,macdonald,thacker}.csv
#
# Output: papers/01_review/figures/out/fig02_verification.{pdf,png}
#
# Run:
#   Rscript papers/01_review/figures/R/fig02_verification.R

library(ggplot2)
library(readr)
library(dplyr)
library(patchwork)
source(here::here("examples/huasco_2d_phase2/figures/R/theme_paper.R"))
setup_paper_theme(journal = "elsevier")

data_dir <- here::here("papers/01_review/figures/data")
stoker <- read_csv(file.path(data_dir, "verif_stoker.csv"), show_col_types = FALSE)
macd   <- read_csv(file.path(data_dir, "verif_macdonald.csv"), show_col_types = FALSE)
thac   <- read_csv(file.path(data_dir, "verif_thacker.csv"), show_col_types = FALSE)

col_an  <- "grey20"            # analytical reference (line)
col_sim <- pal_wong[6]         # simulated (points), Wong blue

# No numeric error annotations on the panels: the authoritative
# metrics live in Table 1 / §3 (computed over the benchmark-specific
# regions, e.g. the Stoker rarefaction fan, the 2D Thacker interior).
# Recomputing them here over a 1D slice would print subtly different
# numbers and create a figure/text inconsistency. The figure's job is
# the visual overlay; the caption points to Table 1.

# Shared legend handled by a manual colour scale.
overlay_scale <- scale_colour_manual(
  values = c("analytical" = col_an, "simulated" = col_sim), name = NULL)

# Decimate the dense Stoker profile so the points are readable.
stoker_pts <- stoker |> filter(row_number() %% 8 == 1)

p_a <- ggplot(stoker, aes(x = x)) +
  geom_line(aes(y = h_analytical, colour = "analytical"), linewidth = 0.5) +
  geom_point(data = stoker_pts, aes(y = h_sim, colour = "simulated"),
             size = 0.7, alpha = 0.9) +
  overlay_scale +
  labs(x = "x [m]", y = "h [m]",
       subtitle = "(a) Stoker dam-break (t = 4 s)") +
  theme(plot.subtitle = element_text(size = 8), legend.position = "none")

p_b <- ggplot(macd, aes(x = x)) +
  geom_line(aes(y = h_analytical, colour = "analytical"), linewidth = 0.5) +
  geom_point(aes(y = h_sim, colour = "simulated"), size = 0.9, alpha = 0.9) +
  overlay_scale +
  # Zoom the y-axis around h_n so the <0.1% drift is visible.
  coord_cartesian(ylim = {
    hn <- macd$h_analytical[1]
    c(hn * 0.985, hn * 1.015)
  }) +
  labs(x = "x [m]", y = "h [m]",
       subtitle = "(b) MacDonald uniform flow (steady)") +
  theme(plot.subtitle = element_text(size = 8), legend.position = "none")

p_c <- ggplot(thac, aes(x = x)) +
  geom_line(aes(y = h_analytical, colour = "analytical"), linewidth = 0.5) +
  geom_point(data = thac |> filter(row_number() %% 2 == 1),
             aes(y = h_sim, colour = "simulated"), size = 0.7, alpha = 0.9) +
  overlay_scale +
  labs(x = "x [m]", y = "h [m]",
       subtitle = "(c) Thacker oscillation (t = T/2)") +
  theme(plot.subtitle = element_text(size = 8), legend.position = "top")

final_fig <- (p_a | p_b | p_c) + plot_layout(nrow = 1)

out_dir <- here::here("papers/01_review/figures/out")
ggsave(file.path(out_dir, "fig02_verification.pdf"), final_fig,
       width = 18.0, height = 6.2, units = "cm", device = cairo_pdf, bg = "white")
ggsave(file.path(out_dir, "fig02_verification.png"), final_fig,
       width = 18.0, height = 6.2, units = "cm", device = ragg::agg_png,
       bg = "white", dpi = 300)

cat("Saved fig02_verification to papers/01_review/figures/out/\n")
cat("(authoritative error metrics: Table 1 / §3 of the manuscript)\n")
