# fig03_uk_ea_t6.R — methods-paper Figure 3.
#
# UK Environment Agency 2D benchmark Test 6 (urban dam-break through a
# building array, §3.6): the depth field at t = 30 s on the 500 × 100 m
# domain, with the six building footprints overlaid. Demonstrates the
# wetting/drying, the buildings staying dry, and the wake structure
# downstream of the obstruction array.
#
# Input (generated by `gen_verification_data` example):
#   papers/01_review/figures/data/verif_uk_ea_t6.csv  (x, y, h, is_building)
#
# Output: papers/01_review/figures/out/fig03_uk_ea_t6.{pdf,png}
#
# Run:
#   Rscript papers/01_review/figures/R/fig03_uk_ea_t6.R

library(ggplot2)
library(readr)
library(dplyr)
library(scico)
source(here::here("examples/huasco_2d_phase2/figures/R/theme_paper.R"))
setup_paper_theme(journal = "elsevier")

d <- read_csv(
  here::here("papers/01_review/figures/data/verif_uk_ea_t6.csv"),
  show_col_types = FALSE
)

# Wet cells only (mask dry + building cells) for the depth raster.
wet <- d |> filter(is_building == 0 & h > 0.01)

# Building footprints (must match BUILDINGS in the example / test).
buildings <- data.frame(
  xmin = c(150, 150, 200, 250, 250, 320),
  xmax = c(170, 170, 220, 270, 270, 360),
  ymin = c(20,  60,  40,  20,  60,  35),
  ymax = c(40,  80,  60,  40,  80,  65)
)

depth_max <- max(wet$h, na.rm = TRUE)

p <- ggplot() +
  geom_raster(data = wet, aes(x = x, y = y, fill = h)) +
  scale_fill_scico(palette = "devon", direction = -1, end = 0.9,
                   name = "depth\n[m]", limits = c(0, depth_max),
                   breaks = pretty(c(0, depth_max), n = 5)) +
  geom_rect(data = buildings,
            aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
            fill = "grey55", colour = "grey25", linewidth = 0.25) +
  # Dam location reference.
  annotate("segment", x = 100, xend = 100, y = 0, yend = 100,
           linetype = "22", colour = "grey40", linewidth = 0.3) +
  annotate("text", x = 100, y = 103, label = "dam", size = 2.4,
           colour = "grey30", vjust = 0) +
  coord_fixed(xlim = c(0, 500), ylim = c(0, 100), expand = FALSE,
              clip = "off") +
  labs(x = "x [m]", y = "y [m]") +
  theme(legend.position = "right",
        legend.title = element_text(size = 7),
        legend.text = element_text(size = 6),
        legend.key.width = unit(0.25, "cm"),
        legend.key.height = unit(0.5, "cm"),
        plot.margin = margin(6, 4, 2, 2, "pt"))

out_dir <- here::here("papers/01_review/figures/out")
# 5:1 domain → landscape strip. 18 cm wide, height set by aspect + legend.
ggsave(file.path(out_dir, "fig03_uk_ea_t6.pdf"), p,
       width = 18.0, height = 5.2, units = "cm", device = cairo_pdf, bg = "white")
ggsave(file.path(out_dir, "fig03_uk_ea_t6.png"), p,
       width = 18.0, height = 5.2, units = "cm", device = ragg::agg_png,
       bg = "white", dpi = 300)

cat("Saved fig03_uk_ea_t6 to papers/01_review/figures/out/\n")
cat(sprintf("max depth = %.2f m, wet cells = %d\n", depth_max, nrow(wet)))
